language: node_js
node_js:
    - "iojs"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

notifications:
    email:
        - info@valentineus.link

before_install:
    - npm install --only=production
    - npm install --only=development