language: node_js
node_js:
    - "iojs"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

notifications:
    email:
        - info@valentineus.link

install:
    - npm install --global nyc
    - npm install --only=production
    - npm install --only=development

script:
    - nyc npm run test
    - nyc report --reporter=lcov

after_success:
    - nyc report --reporter=lcov
    - codacy-coverage