language: node_js
node_js:
    - "iojs"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

notifications:
    email:
        - info@valentineus.link

before_install:
    - npm install --only=production
    - npm install --only=development

install:
    - npm install --global mocha-lcov-reporter
    - npm install --global coveralls
    - npm install --global istanbul

before_script:
    - npm run build

script:
    - istanbul cover ./node_modules/mocha/bin/mocha tests/index.js --report lcovonly -- -R spec

after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js