language: node_js
node_js:
    - "iojs"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

env:
    - CODECOV_TOKEN="61766506-526c-4fa0-9c17-539b4f14fc3d"

notifications:
    email:
        - info@valentineus.link

before_install:
    - npm install --only=production
    - npm install --only=development

install:
    - npm install --global source-map-support
    - npm install --global istanbul
    - npm install --global codecov

before_script:
    - npm run build

script:
    - istanbul cover ./node_modules/mocha/bin/mocha tests/index.js -- -R spec
    - codecov