language: node_js
node_js:
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

notifications:
    email:
        - info@valentineus.link

before_install:
    - npm install --global nyc
    - npm install --global codacy-coverage

install:
    - npm install --only=production
    - npm install --only=development

script:
    - nyc npm run test
    - nyc report --reporter=lcov

after_success:
    - nyc report --reporter=lcov
    - cat ./coverage/lcov.info | codacy-coverage